version : '3'
services:
  ruoyi-mysql:
    container_name: ruoyi-mysql
    image: mysql:5.7
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/logs
      - ./mysql/data:/var/lib/mysql
      - ./mysql/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: 'ry-cloud'
      MYSQL_ROOT_PASSWORD: 123765 
  ruoyi-nacos:
    container_name: ruoyi-nacos
    image: nacos/nacos-server:2.0.3
    environment:
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=ruoyi-mysql #Mysql的主机号，同一台机器不能使用IP，直接使用容器名
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=ry-config
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=123765
      - MYSQL_DATABASE_NUM=1
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=10000&socketTimeout=30000 #控制数据库连接时间
      - JVM_XMS=256m
      - JVM_XMX=256m
      - JVM_XMN=256m
    volumes:
      - ./nacos/logs/:/home/nacos/logs/
      - ./nacos/conf:/home/nacos/init.d/
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    depends_on:
      - ruoyi-mysql
    links: 
      - ruoyi-mysql
  ruoyi-redis:
    container_name: ruoyi-redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/home/ruoyi/redis/redis.conf
      - ./redis/data:/data
    command: redis-server /home/ruoyi/redis/redis.conf
  ruoyi-gateway:
    container_name: ruoyi-gateway
    build: ./wanyi/gateway
    ports:
      - "8080:8080"
    depends_on:
      - ruoyi-redis
      - ruoyi-nacos
    links:
      - ruoyi-redis
      - ruoyi-nacos
  ruoyi-auth:
    container_name: ruoyi-auth
    build: ./wanyi/auth
    ports:
      - "9200:9200"
    depends_on:
      - ruoyi-redis
      - ruoyi-nacos
    links:
      - ruoyi-redis
      - ruoyi-nacos
  ruoyi-front:
    container_name: ruoyi-front
    build: ./wanyi/front
    ports:
      - "9301:9301"
    depends_on:
      - ruoyi-redis
      - ruoyi-nacos
    links:
      - ruoyi-redis
      - ruoyi-nacos
  ruoyi-modules-system:
    container_name: ruoyi-modules-system
    build: ./wanyi/modules/system
    ports:
      - "9201:9201"
    depends_on:
      - ruoyi-redis
      - ruoyi-mysql
      - ruoyi-nacos
    links:
      - ruoyi-redis
      - ruoyi-mysql
      - ruoyi-nacos
  ruoyi-modules-file:
    container_name: ruoyi-modules-file
    build: ./wanyi/modules/file
    ports:
      - "9300:9300"
    volumes:
      - ./wanyi/modules/file/uploadPath:/home/ruoyi/uploadPath
    depends_on:
      - ruoyi-nacos
      - ruoyi-mysql
    links:
      - ruoyi-nacos
      - ruoyi-mysql
  ruoyi-visual-monitor:
    container_name: ruoyi-visual-monitor
    build: ./wanyi/visual/monitor
    ports:
      - "9100:9100"
    depends_on:
      - ruoyi-nacos
    links:
      - ruoyi-nacos
  ruoyi-nginx:
    container_name: ruoyi-nginx
    image: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/html/dist:/home/ruoyi/projects/ruoyi-ui
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - ruoyi-gateway
    links:
      - ruoyi-gateway

